- name: Uninstall topgrade on macOS systems via Homebrew
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Check for brew binary
      ansible.builtin.raw: which brew
      check_mode: false
      changed_when: false
      failed_when: which_brew_result.rc > 1
      register: which_brew_result

    - name: Uninstall topgrade using Homebrew
      community.general.homebrew:
        name: topgrade
        state: absent

- name: Uninstall topgrade on FreeBSD systems via packages
  when: ansible_distribution == 'FreeBSD'
  block:
    - name: Uninstall topgrade using FreeBSD packages
      become: true
      community.general.pkgng:
        name: topgrade
        state: absent

- name: Uninstall topgrade from Debian-based systems
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Uninstall Debian topgrade package
      ansible.builtin.apt:
        name: topgrade
        state: absent
